### ISSUE TITLE
[Feature request] Add multilanguage support

### ISSUE THREAD

**Issue by lozalojo** [moo-man/FVTT-SelectiveShow#2]
Please add the framework for translating the module to other languages (as other modules do, with an en.json file in a lang folder with keys that we can translate).

I have translated more than 10 modules and this one doesnt support translating.

Thanks!

**Comment by moo-man** [comment]
Thanks for the offer to translate it, however I'm not sure if I'm going to bother since this module is about to be deprecated with a core feature.

**Comment by lozalojo** [comment]
Has it been announced by Atropos? In 0.7.4? Didnt know

**Comment by moo-man** [comment]
https://gitlab.com/foundrynet/foundryvtt/-/issues/2842 planned for 0.7.4, but seems it might slip off to 5 or 6

**Comment by lozalojo** [comment]
Then, there is no reason to translate it, better wait for official support.

Thanks!

**Comment by moo-man** [comment]
#4
